permalink: /:title 

pygments: true

markdown: kramdown

title : UGRR Orbitist
tagline: Anti-slavery activists of the 1800s
author : 
  name : Orbitist Support
  email : support@orbitist.com
  github : Orbitist
  twitter : TheOrbitist
  web : http://www.orbitist.com

production_url : orbitist.com/ugrr_atlas

baseurl : http://orbitist.com/ugrr_atlas
        
analytics :
  google : 
    tracking_id : ''


authors:
  ngunner:
    name: Nicholas Gunner
    display_name: Nicholas Gunner
    bio: Founder of Orbitist. New Media Manager at SUNY Fredonia. Multimedia Storyteller.
    image: http://orbitist.s3.amazonaws.com/_toplevel/images/profile-images/ngunner.jpg
    email: gunnernr@gmail.com
    web: http://www.nicholasgunner.com
    twitter: nicholas_gunner
    github: ngunner
  dshepard:
    name: Douglas H. Shepard
    display_name: Doug Shepard
    bio: UGRR Researcher based in Fredonia, NY
    image: http://www.fredonia.edu/department/english/images/dougshepard.jpg
    email: wshepard@netsync.net
  wstraight:
    name: Wendy Straight
    display_name: Wendy Straight
    bio: UGRR Researcher based in Fredonia, NY
    image: https://www.fig.net/pub/tf/unrep/200003/Image116.gif
    email: wendy@netsync.net

  
timezone : America/New_York


prose:
  siteurl: 'http://www.orbitist.com/ugrr'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /_site
    - CNAME
    - /css
    - index.html
    - /plugins
    - README.MD
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published?"
          value: "true"
      - name: "listed"
        field:
          element: "checkbox"
          label: "Listed?"
          value: "true"
      - name: "sponsored"
        field:
          element: "checkbox"
          label: "Sponsored?"
          value: "true"
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments?"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "description"
        field:
          element: "text"
          label: "Description"
      - name: "author"
        field:
          element: "text"
          label: "Author username"
      - name: "sources"
        field:
          element: "text"
          label: "Enter sources here."
      - name: "image"
        field:
          element: "text"
          label: "Featured image"
      - name: "latitude"
        field:
          element: "text"
          label: "Latitude"
      - name: "longitude"
        field:
          element: "text"
          label: "Longitude"
      - name: "zoom"
        field:
          element: "text"
          label: "Initial zoom level"
      - name: "title"
        field:
          element: "text"
          label: "Slide title"
      - name: "maxZoom"
        field:
          element: "text"
          label: "Maximum zoom level"
      - name: "basemap"
        field:
          element: "select"
          label: "Base Map"
          placeholder: "Choose basemap"
          options:
            - name: "Orbitist streets"
              value: "orbitist.ie90k9cc"
            - name: "Orbitist satellite"
              value: "orbitist.if1em1bg"
            - name: "Orbitist terrain"
              value: "orbitist.if61m31c"
            - name: "Orbitist light"
              value: "orbitist.ina586ah"
      - name: "tilemilltiles"
        field:
          element: "text"
          label: "Tilemill tiles code"
      - name: "cartodbapi"
        field:
          element: "text"
          label: "CartoDB API Code"
      - name: "orbitistapi"
        field:
          element: "text"
          label: "Orbitist API code"
      - name: "customjs"
        field:
          element: "text"
          label: "Link to custom JS file"
